
Cerberus_HookThisFile();

g_xalAtath = g_soundLibrary:Inherit({ m_sDisplayName = "Xal'Atath", m_sDataName = "XalAtath" });
g_xalAtath.m_generalSoundFilesList =
{
	1391143,--"Sound/creature/xalatath_blade_of_the_black_empire/vo_703_xalatath_blade_of_the_black_empire_13.ogg",	-- So much fury in this soul! It will be a good harvest!
	1391156,--"Sound/creature/xalatath_blade_of_the_black_empire/vo_703_xalatath_blade_of_the_black_empire_26.ogg",	-- I long for the day our masters can truly pass into this realm. (...)
	1391161,--"Sound/creature/xalatath_blade_of_the_black_empire/vo_703_xalatath_blade_of_the_black_empire_31.ogg",	-- It is ironic that the weakest of us may be the ultimate victor. (...)
	1391166,--"Sound/creature/xalatath_blade_of_the_black_empire/vo_703_xalatath_blade_of_the_black_empire_36.ogg",	-- Did you feel it cease to exist?
	1391175,--"Sound/creature/xalatath_blade_of_the_black_empire/vo_703_xalatath_blade_of_the_black_empire_45.ogg",	-- I know the naaru consider us horrors to be resisted. We do not share this view. (...)
	1391177,--"Sound/creature/xalatath_blade_of_the_black_empire/vo_703_xalatath_blade_of_the_black_empire_47.ogg",	-- Do the naaru speak of the eternal conflict? (...)
	1391200,--"Sound/creature/xalatath_blade_of_the_black_empire/vo_703_xalatath_blade_of_the_black_empire_70.ogg",	-- The fallen elves cower behind their wall. They know no other way.
	1580976,--"Sound/creature/xalatath_blade_of_the_black_empire/vo_72_xalatath_blade_of_the_black_empire_04_f.ogg",	-- At times it seems the naga begg for scraps from the legion's table (...)
	1581003,--"Sound/creature/xalatath_blade_of_the_black_empire/vo_72_xalatath_blade_of_the_black_empire_22_f.ogg",	-- You were a good choice. No other wielder have murdered their way accross the continent quite like you have. (...)
	1581004,--"Sound/creature/xalatath_blade_of_the_black_empire/vo_72_xalatath_blade_of_the_black_empire_23_f.ogg",	-- The Light would have your kind remain obedient and stagnant. I offer the gifts of freedom and strength. (...)
	1581005,--"Sound/creature/xalatath_blade_of_the_black_empire/vo_72_xalatath_blade_of_the_black_empire_24_f.ogg",	-- Your allies consider me a bad influence; yet all i've ever done is speed you along the path you chose.
	1581006,--"Sound/creature/xalatath_blade_of_the_black_empire/vo_72_xalatath_blade_of_the_black_empire_25_f.ogg",	-- I can feel the pulse of your world quickening. Soon, all will be drenched in its life blood.

	-- @TwoSouls additions
	1391130,--"Sound/creature/xalatath_blade_of_the_black_empire/vo_703_xalatath_blade_of_the_black_empire_02.ogg",	-- Ihr dagegen...
	1391131,--"Sound/creature/xalatath_blade_of_the_black_empire/vo_703_xalatath_blade_of_the_black_empire_03.ogg",	-- Ja, wir wollen uns...
	1391132,--"Sound/creature/xalatath_blade_of_the_black_empire/vo_703_xalatath_blade_of_the_black_empire_04.ogg",	-- Die Kultisten...
	1391135,--"Sound/creature/xalatath_blade_of_the_black_empire/vo_703_xalatath_blade_of_the_black_empire_05.ogg",	-- Ein Diener der alten G?tter...
	1391136,--"Sound/creature/xalatath_blade_of_the_black_empire/vo_703_xalatath_blade_of_the_black_empire_06.ogg",	-- Dort, ein Diener von...
	1391137,--"Sound/creature/xalatath_blade_of_the_black_empire/vo_703_xalatath_blade_of_the_black_empire_07.ogg",	-- Seht ihr, der Wirt kann nicht...
	1391138,--"Sound/creature/xalatath_blade_of_the_black_empire/vo_703_xalatath_blade_of_the_black_empire_08.ogg",	-- Ein Verr?er...
	1391140,--"Sound/creature/xalatath_blade_of_the_black_empire/vo_703_xalatath_blade_of_the_black_empire_10.ogg",	-- Ein targischer Ort...
	1391157,--"Sound/creature/xalatath_blade_of_the_black_empire/vo_703_xalatath_blade_of_the_black_empire_27.ogg",	-- Die N?e zur Leere...
	1391159,--"Sound/creature/xalatath_blade_of_the_black_empire/vo_703_xalatath_blade_of_the_black_empire_29.ogg",	-- Wir k?nnten in diesem Konflik...
	1391172,--"Sound/creature/xalatath_blade_of_the_black_empire/vo_703_xalatath_blade_of_the_black_empire_42.ogg",	-- Keiner unserer Diener...
	1391173,--"Sound/creature/xalatath_blade_of_the_black_empire/vo_703_xalatath_blade_of_the_black_empire_43.ogg",	-- Die Maueren...
	1391174,--"Sound/creature/xalatath_blade_of_the_black_empire/vo_703_xalatath_blade_of_the_black_empire_44.ogg",	-- Die Erforschung der Leere...
	1391180,--"Sound/creature/xalatath_blade_of_the_black_empire/vo_703_xalatath_blade_of_the_black_empire_50.ogg",	-- Eine weitere Saat der Verderbnis
	1391181,--"Sound/creature/xalatath_blade_of_the_black_empire/vo_703_xalatath_blade_of_the_black_empire_51.ogg",	-- Fast ganz entschwunden...
	1391182,--"Sound/creature/xalatath_blade_of_the_black_empire/vo_703_xalatath_blade_of_the_black_empire_52.ogg",	-- Das Gef?gnis von...
	1391190,--"Sound/creature/xalatath_blade_of_the_black_empire/vo_703_xalatath_blade_of_the_black_empire_60.ogg",	-- Hier ist jemand...
	1391197,--"Sound/creature/xalatath_blade_of_the_black_empire/vo_703_xalatath_blade_of_the_black_empire_67.ogg",	-- Lasst euch nich von gro?n...
	1580897,--"Sound/creature/xalatath_blade_of_the_black_empire/vo_72_xalatath_blade_of_the_black_empire_02_f.ogg",	-- Lange hat er eure Welt heimgesucht...
	1580979,--"Sound/creature/xalatath_blade_of_the_black_empire/vo_72_xalatath_blade_of_the_black_empire_07_f.ogg",	-- Die einen Invasoren verderben....
	1580980,--"Sound/creature/xalatath_blade_of_the_black_empire/vo_72_xalatath_blade_of_the_black_empire_08_f.ogg",	-- Lasst mich in diesem Kampf...
	1580993,--"Sound/creature/xalatath_blade_of_the_black_empire/vo_72_xalatath_blade_of_the_black_empire_12_f.ogg",	-- So viel Tod ?berall...
	1580995,--"Sound/creature/xalatath_blade_of_the_black_empire/vo_72_xalatath_blade_of_the_black_empire_14_f.ogg",	-- Seit der Schlacht von...
	1581000,--"Sound/creature/xalatath_blade_of_the_black_empire/vo_72_xalatath_blade_of_the_black_empire_19_f.ogg",	-- Dieser Konflikt ist nur der Schatten....
	1581001,--"Sound/creature/xalatath_blade_of_the_black_empire/vo_72_xalatath_blade_of_the_black_empire_20_f.ogg",	-- Es dauerte ewig nach der Zerschlagung...
	1686159,--"Sound/creature/xalatath_blade_of_the_black_empire/vo_73_xalatath_blade_of_the_black_empire_01_f.ogg",	-- So viel M?he, so viel..
	1686164,--"Sound/creature/xalatath_blade_of_the_black_empire/vo_73_xalatath_blade_of_the_black_empire_06_f.ogg",	-- Lahme Mythen...
	1686318,--"Sound/creature/xalatath_blade_of_the_black_empire/vo_73_xalatath_blade_of_the_black_empire_08_f.ogg",	-- Die Raupe...
	1686319,--"Sound/creature/xalatath_blade_of_the_black_empire/vo_73_xalatath_blade_of_the_black_empire_09_f.ogg",	-- Er br?stet sich...
	1686322,--"Sound/creature/xalatath_blade_of_the_black_empire/vo_73_xalatath_blade_of_the_black_empire_12_f.ogg",	-- Das nenne ich...
	1686323,--"Sound/creature/xalatath_blade_of_the_black_empire/vo_73_xalatath_blade_of_the_black_empire_13_f.ogg",	-- Schmeckt ihr ihn...
	1686324,--"Sound/creature/xalatath_blade_of_the_black_empire/vo_73_xalatath_blade_of_the_black_empire_14_f.ogg",	-- So viel Potential...
	2530793,--"Sound/creature/xalatath_blade_of_the_black_empire/vo_815_xalatath_blade_of_the_black_empire_01_f.ogg",	-- Gro?rtige Dinge wartena auf uns.
	2530794,--"Sound/creature/xalatath_blade_of_the_black_empire/vo_815_xalatath_blade_of_the_black_empire_02_f.ogg",	-- ?fnet euren Geist f?r die Stimmen.
	2530795,--"Sound/creature/xalatath_blade_of_the_black_empire/vo_815_xalatath_blade_of_the_black_empire_03_f.ogg",	-- Es ist fast soweit...
	2530796,--"Sound/creature/xalatath_blade_of_the_black_empire/vo_815_xalatath_blade_of_the_black_empire_04_f.ogg",	-- Wonach strebt Ihr?
	2530797,--"Sound/creature/xalatath_blade_of_the_black_empire/vo_815_xalatath_blade_of_the_black_empire_05_f.ogg",	-- So viele M?glichkeiten.
	2530798,--"Sound/creature/xalatath_blade_of_the_black_empire/vo_815_xalatath_blade_of_the_black_empire_06_f.ogg",	-- Sagt mir was Ihr begehrt.
	2530800,--"Sound/creature/xalatath_blade_of_the_black_empire/vo_815_xalatath_blade_of_the_black_empire_08_f.ogg",	-- St?ke schwindet... Brauche Blut...
	2530801,--"Sound/creature/xalatath_blade_of_the_black_empire/vo_815_xalatath_blade_of_the_black_empire_09_f.ogg",	-- Wie sch?n wieder die Alte zu sein...
	2530802,--"Sound/creature/xalatath_blade_of_the_black_empire/vo_815_xalatath_blade_of_the_black_empire_10_f.ogg",	-- Ach, es freut mich, dass wir wieder etwas Zeit...
	2530803,--"Sound/creature/xalatath_blade_of_the_black_empire/vo_815_xalatath_blade_of_the_black_empire_11_f.ogg",	-- Ihr und ich -  wir werden zusammen glorreiches...
	2530804,--"Sound/creature/xalatath_blade_of_the_black_empire/vo_815_xalatath_blade_of_the_black_empire_12_f.ogg",	-- Ich wei? es ist vielleicht befremdlich...
	2530807,--"Sound/creature/xalatath_blade_of_the_black_empire/vo_815_xalatath_blade_of_the_black_empire_15_f.ogg",	-- Behaltet mich nah bei euch...
	2530811,--"Sound/creature/xalatath_blade_of_the_black_empire/vo_815_xalatath_blade_of_the_black_empire_19_f.ogg",	-- K?nnt ihr es sehen?
	2530815,--"Sound/creature/xalatath_blade_of_the_black_empire/vo_815_xalatath_blade_of_the_black_empire_23_f.ogg",	-- Ich wusste das ihr die richtige Wahl seid...
	2530816,--"Sound/creature/xalatath_blade_of_the_black_empire/vo_815_xalatath_blade_of_the_black_empire_24_f.ogg",	-- Einmal mehr beweisst ihr euch meiner Bwunderung...
	2530819,--"Sound/creature/xalatath_blade_of_the_black_empire/vo_815_xalatath_blade_of_the_black_empire_27_f.ogg",	-- Unsere Begegnung war kein Zufall...
	2530820,--"Sound/creature/xalatath_blade_of_the_black_empire/vo_815_xalatath_blade_of_the_black_empire_28_f.ogg",	-- Uns ist Gro?s bestimmt...
	2530826,--"Sound/creature/xalatath_blade_of_the_black_empire/vo_815_xalatath_blade_of_the_black_empire_34_f.ogg",	-- Ach ja? Das werden wir noch sehen.
	2530829,--"Sound/creature/xalatath_blade_of_the_black_empire/vo_815_xalatath_blade_of_the_black_empire_37_f.ogg",	-- Unser Ziel liegt voor uns...
	2530832,--"Sound/creature/xalatath_blade_of_the_black_empire/vo_815_xalatath_blade_of_the_black_empire_40_f.ogg",	-- Ich bin so froh, dass ihr euren Geist...
	2530839,--"Sound/creature/xalatath_blade_of_the_black_empire/vo_815_xalatath_blade_of_the_black_empire_47_f.ogg",	-- Die Naga an euer K?ste sind nicht von Belang...
	2530843,--"Sound/creature/xalatath_blade_of_the_black_empire/vo_815_xalatath_blade_of_the_black_empire_51_f.ogg",	-- Ein fairer Handel...
	2530846,--"Sound/creature/xalatath_blade_of_the_black_empire/vo_815_xalatath_blade_of_the_black_empire_54_f.ogg",	-- Geben wir nicht ein gro?rtiges Team ab?
	2530968,--"Sound/creature/xalatath_blade_of_the_black_empire/vo_815_xalatath_blade_of_the_black_empire_55_f.ogg",	-- Am?siert ihr euch?
	2531112,--"Sound/creature/xalatath_blade_of_the_black_empire/vo_815_xalatath_blade_of_the_black_empire_58_f.ogg",	-- Solcher Ruhm erwartet euch...
};
g_xalAtath.m_deathSoundFilesList =
{
	1391162,--"Sound/creature/xalatath_blade_of_the_black_empire/vo_703_xalatath_blade_of_the_black_empire_32.ogg",	-- Delicious
	1391163,--"Sound/creature/xalatath_blade_of_the_black_empire/vo_703_xalatath_blade_of_the_black_empire_33.ogg",	-- Every little death helps
	1391164,--"Sound/creature/xalatath_blade_of_the_black_empire/vo_703_xalatath_blade_of_the_black_empire_34.ogg",	-- Enjoy that?
	1391165,--"Sound/creature/xalatath_blade_of_the_black_empire/vo_703_xalatath_blade_of_the_black_empire_35.ogg",	-- Boring
	1391167,--"Sound/creature/xalatath_blade_of_the_black_empire/vo_703_xalatath_blade_of_the_black_empire_37.ogg",	-- *Long laugh*
	1391194,--"Sound/creature/xalatath_blade_of_the_black_empire/vo_703_xalatath_blade_of_the_black_empire_64.ogg",	-- *Short laugh*
};
